include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
    
linter:
  rules:
    - prefer_relative_imports
    - prefer_const_declarations
    - prefer_const_constructors

